# Generated by Django 4.2.1 on 2023-05-30 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("testapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="age",
            new_name="id",
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=20)),
                ("desc", models.CharField(max_length=100)),
                (
                    "priority",
                    models.CharField(
                        choices=[("L", "LOW"), ("M", "MEDIUM"), ("H", "HIGH")],
                        max_length=1,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="testapp.user"
                    ),
                ),
            ],
        ),
    ]
